version: '3'

networks:
  default:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: superPW
      MYSQL_USER: femto-booked
      MYSQL_PASSWORD: femto-pass
      MYSQL_DATABASE: booked
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      #      - ./www/database_schema:/sql
    restart: always
  
  php:
    build:
      context: ./php-img
    volumes:
      - ./www:/var/www/
      - ./logs:/logs/
    restart: always
  
  bwebserver:
    image: nginx
    depends_on:
      - "mariadb"
      - "php"
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/
      - ./sites:/etc/nginx/conf.d
